package com.chefkix.notification.enums;

public enum NotificationType {
    FOLLOW,
    NEW_FOLLOWER,

    POST_LIKE,
    POST_COMMENT,
    RECIPE_LIKED,
    USER_MENTION,

    XP_AWARDED,
    LEVEL_UP,
    BADGE_EARNED,
    CREATOR_BONUS,

    STREAK_WARNING,
    POST_DEADLINE,
    CHALLENGE_AVAILABLE,
    CHALLENGE_REMINDER,
    WEEKEND_NUDGE,
    PANTRY_EXPIRING,

    ROOM_INVITE,
    CO_CHEF_TAGGED,

    DUEL_INVITE,
    DUEL_ACCEPTED,
    DUEL_DECLINED,
    DUEL_COMPLETED,
    DUEL_EXPIRED,

    JOIN_REQUESTED,
    MEMBER_JOINED,
    JOIN_REQUEST_APPROVED,

    //Story
    STORY_INTERACTION
}
